---
title: "Interesting R Examples"
author: "Zeynep Hasgül - IE582 - Fall 2020"
---
```{r,echo=FALSE,results="hide"}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```

1. [Fixing Covid-19 Case Number and Death Toll Underreporting](https://www.neurosynergy.io/articles/fixingcovid-19underreporting)

    Developed by Matt Maciejewski, this Shiny app focuses on the correction of underreported Covid-19 case and death counts using a reference country based on Lachmann et al. (2020), and via a multiplicative estimator for total deaths and cases. The estimator will be turned into a posterior prediction once data becomes available.

2. [Turkey vs. Germany: COVID-19](https://datageeek.wordpress.com/2020/05/31/turkey-vs-germany-covid-19/)

    This article compares efforts by Turkey and Germany to control the pandemic, and tests several regression models. Two variables are used for compared parameters; the number of daily new cases and daily new deaths.

3. [Scraping Google Covid-19 community movement data from PDF figures](https://datageeek.wordpress.com/2020/05/31/turkey-vs-germany-covid-19/)

    This article explains how to scrape data from a Google site that tracks movements of people. The author uses the {tidycovid19} R package and prepares an analysis of Germany and then across countries.


4. [COVID-19: Analyze Mobility Trends with R](https://blog.ephorie.de/covid-19-analyze-mobility-trends-with-r)

    This article analyzes mobility trends with R using anonymized and aggregated Apple’s mobility data available to the public. The article presents a R function to return the data in a well-structured format for countries and major cities, and to visualize the drop in vehicular and pedestrian movement caused by the pandemic.

5. [covid19 & some computational-corpus linguistics](https://www.jtimm.net/2020/05/26/corp-comp-ling-covid19/)

    This article analyzes all tweets generated by the 535 voting members of the US Congress during the second session of the 116th Congress. More specifically, the author considered the usage of COVID19-related terms as a function of both time and party affiliation. He also investigates the conceptual relatedness of COVID19-relevant terms using a GloVe model and multi-dimensional scaling.
